version: 0.2
phases: 
  install: 
    runtime-versions:
      nodejs:14
    commands: 
      - echo "Install dependencies..." 
      - npm install 
      - npm install -g @angular/cli@10.0.8
    build:
      commands:
        - echo "Build Angular Projects..."
        - ng build --prod
    post_build:
      commands:
        - echo "Updating files in the S3 bucket..." 
        - aws s3 sync dist/github-s3-angular-app/ s3:// 

